### PR TITLE
config/ot2_defconfig: select screen, python3_curses

### PR DESCRIPTION
**Pull request by theosanderson**
The OpenTrons app interface does not allow branching protocols ("how many samples do you want to run?"), etc. The easy way to implement these sorts of things is in old fashioned Python scripts run in a terminal. But for this to be reliable it needs to be possible to resume a terminal session after disconnecting (the Jupyter terminal gets some of the way there but still doesn't really suit my needs).

Therefore it would be great to have `screen`. Screen depends on curses, so we may as well bring in the curses python library too which will allow pip installing other modules that depend on it.

I have tested these two packages on an OT2, albeit in a very slightly different configuration, partly due to #87. 

I realise space is at a premium and am attempting to restrain myself..

### CODE REVIEW

**Comment by mcous** [comment]
I just spend a fair amount of time SSH'd into my robots for testing #94, and I gotta say this feels like a good (and important) addition to the SSH-into-robot workflow.

@theosanderson I'm more personally familiar with tmux over screen; out of curiosity did you consider that for this PR, too? If so, I'd love to hear reasoning for picking screen

**Comment by theosanderson** [comment]
Hi @mcous, no I didn't consider that. Screen happens to be what I'm used to, but I should probably adapt to tmux anyway. Definitely happy for you to go with that instead!

**Comment by theosanderson** [comment]
Just let me know if you want me to change the PR, but apparently there were issues with CI from non-OTers so it may be easier for you to make a new one. Tmux also depends on Curses so keeping the Python package makes (I think) sense.

**Comment by mcous** [comment]
@theosanderson yeah, I think I can handle it to make sure we get a good CI run out of it. Wrapped up in some connectivity work which is taking priority but I'm still hopeful this is something we can sneak into the 3.20 release

**Comment by mcous** [comment]
Update on this PR: we just pushed out version 3.20.0 of the app + robot software, which included a large number of changes to robot connectivity, timekeeping, and calibration (and some contributions from you, @theosanderson!). Due to the relative size of this release and the associated testing burden, this particular PR didn't make the cut.

We still feel strongly about the benefit of having screen and/or tmux functionality given the quality of life improvements they bring to any SSH-based workflow, so I'm happy to commit to getting this ticket into the 3.21 release

**Comment by theosanderson** [comment]
No prob!! Thanks very much for the communication and excited to see this in due course :)

**Comment by mcous** [comment]
Closing this out in favor of #102, which was branched from this PR and includes all changes (including adding screen) + tmux

**Pull request closed without merging**
