### PR TITLE
configs/ot2_defconfig: select ca-certificates, curl, git, grep, sl, wget

### PR DESCRIPTION
**Pull request by sfoster1**
## overview

This PR adds some packages to the OT-2 defconfig to enable more complex workflows:

- `ca-certificates` to make sure the robot has root certs to hit HTTPS stuff
- `git` for pulling stuff from... git
- `curl` and `wget` for making requests and pulling data from HTTP
- `grep` for data and log inspection
- `sl` to make @sfoster1 happy

## review requests

- [ ] can successfully clone a `git` repository via HTTPS
- [ ] can `curl` an HTTPS endpoint
- [ ] can `wget` an HTTPS resource
- [ ] can `grep` something
- [ ] chugga chugga choo choo

### CODE REVIEW

**Comment by theosanderson** [comment]
For info, I branched off this and I am not finding that this works:

```
# git remote add origin https://github.com/theosanderson/covid_serology_ot.git
# git push -u origin master
fatal: Unable to find remote helper for 'https'
# wget "https://bbcnews.com"
wget: not an http or ftp url: https://bbcnews.com
# 

```

Edit: possible this was a copy and paste problem with hidden characters, which I've since encountered. Sorry if this was a bad report!

**Comment by theosanderson** [comment]
Just hit lack of TLS again in terms of just trying to get data from a LIMS server - increasingly everything is HTTPS nowadays, so I think this would be a good fix regardless of git

**Review by sfoster1 — COMMENTED** [review]
Since it's technically still my own PR I can't approve, but I can confirm that git, curl, and wget from https endpoints works, as does the steam locomotive

**Review by mcous — APPROVED** [review]
Approving on behalf of @sfoster1 per his comment above

**Pull request merged**
