### PR TITLE
config/ot2_defconfig: remove systemd-networkd and conflicting eth0 config

### LINKED ISSUE #93: Do not include systemd-networkd in build
## overview

We use NetworkManager to manage our networking configuration, but currently, the OS is being built with both NetworkManager and `systemd-networkd`. These two services are conflicting with each other, as both are trying to exert control over the `eth0` interface.

In the worst case, a race condition between the two can cause the OT-2 to lose its IPv4LL address on Ethernet carrier interruptions without attempting to get a new one. We should remove `systemd-networkd` from the build.

This network manager conflict appears to be the root cause of Opentrons/opentrons#5654

## implementation details

I'm not sure why, exactly, `systemd-networkd` is currently included in our build, because we do not specify its inclusion

### LINKED ISSUE #5654: bug: Robot OS fails to self-assign an IPv4 link-local address
# Overview

**Note**: this ticket is for tracking purposes. Fixes should be directed at the Opentrons/buildroot repository

# Current behavior

Certain networking conditions can cause the Robot OS to bring up it's link-local wired interface without an IPv4 address, rendering the robot unconnectable.

See CPX discovery documentation for more details.

# Steps to reproduce

One way to reproduce this failure is (on macOS) to connect your robot to your computer and allow your computer to go to sleep. If you are also able to connect to your robot via another network interface (e.g. Wi-Fi), you can observe the logs as the wired interface fails to come up properly

# Expected behavior

The Robot OS should never consider the link-local wired interface to be "up" if it has no IPv4 address

### PR DESCRIPTION
**Pull request by mcous**
Setting `BR2_SYSTEM_DHCP` in the defconfig causes buildroot to create a default auto-DHCP interface config for `eth0` using `systemd-networkd`. Since we have our own `eth0` setup via Network Manager, this PR removes the buildroot default eth0 config and marks `systemd-networkd` as explicitly unset, because when installed, they conflict with Network Manager.

Fixes #93, fixes Opentrons/opentrons#5654

Changes to the defconfig created via `menuconfig` and `savedefconfig`. The save caused some other changes to `ot2_defconfig` that I've removed from this PR but that we should probably follow up on:

- `BR2_PACKAGE_PYTHON_OPENTRONS_API` removed
- `BR2_PACKAGE_PYTHON3_BZIP2` removed

I've tested this on a bare RPi and a full robot using the branch build from CI. Everything looks good from my end, and here's what I tested / checked:

- [x] No interfaces defined under `/etc/systemd/network`
- [x] `systemd-networkd` unit is not loaded
    - Also, `networkctl` is not an available binary
- [x] IPv4LL address on `eth0` is not removed until NM takes down the `wired-linklocal` connection
    - Pull the Ethernet cable and observe that NM will wait 5 seconds before taking any action
    - Pull and replug the Ethernet cable within that 5 seconds and note that `eth0` keeps its IPv4LL and the NM connection remains up
- [x] IPv4 DHCP config default still works if Pi is connected to a DHCP router
- [x] IPv4 DHCP still works on any additional U2E adapters you plug into the Pi
    - This is a setup some users have to get the OT-2 onto a DHCP'd wired network without an exposed Ethernet port on the frame

### CODE REVIEW

**Comment by amitlissack** [comment]
`BR2_PACKAGE_PYTHON_OPENTRONS_API` being removed might be due to its being a dependency of robot server package. So that entry is redundant?

A while back I saw the same thing happening with `BR2_PACKAGE_PYTHON_FASTAPI`. Was always being removed. It's already defined in robot-server's `Config.in`.

@sfoster1 ? Am I right?

**Review by amitlissack — APPROVED** [review]
🥇

**Review by b-cooper — APPROVED** [review]
🐋

**Review by sanni-t — APPROVED** [review]
💰

**Review by sfoster1 — APPROVED** [review]
LGTM! Nice!

**Pull request merged**
