### PR TITLE
feat(heater-shaker): add dfu-util package to ot2_defconfig

### PR DESCRIPTION
**Pull request by pmoegenburg**
This package required for firmware upload to stm32 modules, including heater-shaker and thermocycler gen2

### CODE REVIEW

**Comment by laviera** [comment]
@pmoegenburg doesn't thie PR require all the previous ones to be pushed prior ?   One is a major buildroot update

**Comment by sfoster1** [comment]
> @pmoegenburg doesn't thie PR require all the previous ones to be pushed prior ? One is a major buildroot update

I don't think so, this is based on `opentrons-develop` and should apply cleanly

**Comment by laviera** [comment]
@sfoster1 - ok - will need to address the bigger issue soon

**Review by sanni-t — APPROVED** [review]
Tested on a robot and dfu-util works as expected. Also works with https://github.com/Opentrons/opentrons/pull/10307

This PR is good to merge as is but I'd recommend removing the h/s bootloader udev rule while we're at it:

https://github.com/Opentrons/buildroot/blob/ce88f3d950d9e75ef842107e27f98497fa770252/board/opentrons/ot2/rootfs-overlay/etc/udev/rules.d/95-opentrons-modules.rules#L9

Since the bootloader doesn't get registered as an ACM port, this rule doesn't get used but it could cause confusion.

**Pull request merged**
