### PR TITLE
Build: API/buildroot integration

### PR DESCRIPTION
**Pull request by sfoster1**
Integrate the Opentrons API server into Buildroot.

There is a corresponding PR in the monorepo: https://github.com/Opentrons/opentrons/pull/3217

This adds the API server as a buildroot package from a [br2-external-tree](https://buildroot.org/downloads/manual/manual.html#outside-br-custom), which keeps us from having to do weird things involving sdists and manual downloads that wouldn't update properly. It also lets the configuration for the api server live in the monorepo.

This requires that the `opentrons` repo be checked out as a sibling to `buildroot`. This is accomplished in CI by the webhook in this PR: https://github.com/Opentrons/devops/pull/3 (currently deployed in a dev environment).

That webhook will kick off builds based on pushes here or pushes to the monorepo that have matching branches here (with `edge` of the monorepo matching to `opentrons-develop` here). There is currently no special handling for releases.

Closes https://github.com/Opentrons/opentrons/issues/2877

### CODE REVIEW

**Comment by sfoster1** [comment]
Testing:

- Download a build and flash an SD card with it. Boot up a robot with that SD card. The opentrons API server should run and the whole shebang should be discoverable on mDNS
- That's basically it. The app won't detect it as good yet because there's no update server and some (most? a lot?) of the api server functionality might not work, but the whole thing being compiled together and booting is the key.

**Comment by sfoster1** [comment]
The full image (what you flash a new sd card with) can be found [here](https://s3.us-east-2.amazonaws.com/opentrons-buildroot-ci/feeeb0a5-124e-4594-9393-c69026be1ca7/opentrons-buildroot/ot2-fullimage.zip)

**Review by Laura-Danielle — APPROVED** [review]
Robot homes and found it with mDNS! 🕺

**Review by mcous — APPROVED** [review]
💯

**Pull request merged**
