### PR TITLE
feat(system): Full opentrons API compatibility

### PR DESCRIPTION
**Pull request by sfoster1**
This adds the fairly ugly hack script ot-blinkenlights. Because the opentrons
module can't be imported cleanly (it reads configs, might do database migration,
etc) we just find it using importlib.find_loader, put the drivers subdirectory
in the pythonpath, and do the setupgpio tasks. This avoids the situation in
balena where the config migration and db migration actually happen when you run
setup_gpio.

This also blinks the button while you're loading. It runs as early as possible
and should blink during the long boot time while the system expands varfs if
necessary.

We also add some various packages and init scripts.

Enables https://github.com/Opentrons/opentrons/pull/3367

### CODE REVIEW

**Review by mcous — COMMENTED** [review]
Code LGTM but I haven't tested functionality yet. I don't know if this would help the import hackiness, but perhaps now might be a good time to finally switch over to the "official" (i.e. developed by someone from RPi) Python GPIO library for the RPi: https://gpiozero.readthedocs.io/en/stable/

**Comment by sfoster1** [comment]
> Code LGTM but I haven't tested functionality yet. I don't know if this would help the import hackiness, but perhaps now might be a good time to finally switch over to the "official" (i.e. developed by someone from RPi) Python GPIO library for the RPi: https://gpiozero.readthedocs.io/en/stable/

I don't want to do this because their backend looks like it uses either `/dev/gpiomem` or the deprecated sysfs interface, blech. We also don't need all the bitbanged spi stuff.

The thing that would help the import hackery is more structural. We need to split stuff that concerns the robot out of the oepntrons api server and into different python packages so a) people don't install it when they install from pypi and b) you don't have to do hacks like this. So it's out of scope.

**Comment by sfoster1** [comment]
If we want to bring in a new dependency for gpio we should use [libgpiod](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/) which has built in python bindings

**Review by mcous — APPROVED** [review]
☂️

**Pull request merged**
