### PR TITLE
Strip tests from numpy and pandas

### PR DESCRIPTION
**Pull request by mcous**
## Overview

This PR attempts to alleviate #144 by encoding something that we've been doing frequently during development into the production builds: strip various `tests` directories from `numpy` and `pandas` prior to creating a system image.

This should save about:

- Pandas: `7.0M`
- Numpy: `2.5M`
- Total: **9.5M**

**PR should be rebased and merged to preserve commit messages.**

## Notes

- Stripping test files is now a configurable option for both Pandas and Numpy
    - Language: positive - "include test files"
    - Default: no - strip files by default
- Conventions and settings inspired by other packages that do the same sort of thing
    - `package/samba4/Config.in`
    - `package/python-pygame/Config.in`

### CODE REVIEW

**Review by amitlissack — APPROVED** [review]

**Review by SyntaxColoring — COMMENTED** [review]
If we put this fixup in `package/`, it seems like they will be prone to being accidentally overwritten if/when we update these packages from upstream. Should we leave comments saying that they're purposeful Opentrons additions, meant to work around filesystem space problems in `/board/opentrons/ot2`?

**Comment by sfoster1** [comment]
> If we put this fixup in `package/`, it seems like they will be prone to being accidentally overwritten if/when we update these packages from upstream. Should we leave comments saying that they're purposeful Opentrons additions, meant to work around filesystem space problems in `/board/opentrons/ot2`?

Honestly we should 
- Make these gated by `Config.in` flags
- Try and upstream them

**Comment by mcous** [comment]
Results of `./utils/diffconfig`

```shell
❯ ./utils/diffconfig
+BR2_PACKAGE_PYTHON_NUMPY_TESTS n
+BR2_PACKAGE_PYTHON_PANDAS_TESTS n
```

**Comment by mcous** [comment]
Results of robot testing. Going to merge to unblock #151 

- numpy: `2.5M`
- pandas: `7.1M`

### `edge`

```shell
# du -hs numpy
11.7M	numpy
# du -hs pandas
24.4M	pandas
```

### This PR

```shell
# du -hs numpy
9.2M	numpy
# du -hs pandas
17.3M	pandas
```

**Pull request merged**
