### PR TITLE
configs/ot2_defconfig: re-select BR2_PACKAGE_NGINX_HTTP_MAP_MODULE

### PR DESCRIPTION
**Pull request by SyntaxColoring**
Commit 5c84bc0b568363a11c3d7731f055e89421b1af78 removed this because it appeared unused. It turns out it *is* used in the OT-2's nginx.conf, and that commit prevented nginx from launching.

### CODE REVIEW

**Review by sfoster1 — CHANGES_REQUESTED** [review]
I don't think this does anything - that just removes a comment. You need to add `BR2_PACKAGE_NGINX_HTTP_MAP_MODULE=y`.

**Comment by SyntaxColoring** [comment]
I'll test this when the build completes, but I think it actually does have an effect. I did:

1. `./opentrons-build.sh -it ot2_defconfig`
2. `./opentrons-build.sh -it menuconfig`
3. Navigate to the `nginx` subtree and turn this module on
4. Save the file and exit `menuconfig`
5. `./opentrons-build.sh -it savedefconfig`
6. Delete several lines from the diff that looked unrelated to this change

**Comment by SyntaxColoring** [comment]
Confirmed that the OT-2 boots up successfully with this PR.

It is mysterious why removing a line that looks like a comment does, in fact, change the build. I'm personally chalking this up to the `ot2_defconfig` file format being accursed with magicks most deep.

**Review by mcous — APPROVED** [review]
From what I can tell, in an `ot2_defconfig`:

`ot2_defconfig` | default | generated `.config`
--- | --- | ---
`# BR2_PACKAGE_... is not set` | `y` | `# BR2_PACKAGE_... is not set`
`# BR2_PACKAGE_... is not set` | `n` | `# BR2_PACKAGE_... is not set`
Nothing | `y` | `BR2_PACKAGE_...=y`
Nothing | `n` | `# BR2_PACKAGE_... is not set`

Given this weirdness, this change makes sense to me

**Pull request closed without merging**
