### PR TITLE
Add SQLAlchemy

### PR DESCRIPTION
**Pull request by mcous**
## Overview

Companion PR to https://github.com/Opentrons/opentrons/pull/9829

This PR adds SQLAlchemy to the robot's operating system.

### CODE REVIEW

**Comment by mcous** [comment]
Tested on a Raspberry Pi. Using the Python REPL onboard, I was able to:

```python
>>> import sqlalchemy
>>> sqlalchemy.__version__
'1.4.32'
```

**Review by SyntaxColoring — APPROVED** [review]
Looks good to me to merge if this has been tested on a robot!

**Review by sanni-t — APPROVED** [review]
Lgtm if it works on a robot!

**Review by y3rsh — APPROVED** [review]
Works on my robot.

**Pull request merged**
